config/routes.rb
Rails.application.routes.draw do
  # get "pages/exempla", to: "pages#exempla"
  namespace :pages do
    get "/exempla", to: "exempla" # equivalent to <get "pages/exempla", to: "pages#exempla"> outside of namespace
    get "/index", to: "index"
  end

  namespace :exempla do
    resources :products
  end

  namespace :coreman do
    resources :entities
  end

  namespace :authentication do
    resource :session
    resources :passwords, param: :token
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/authentication/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/authentication/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :email_address, uniqueness: true

  has_many :entities, dependent: :destroy

  def set_defaults
    self.confirmed_email = false
  end
end

app/models/coreman/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :entity_names, dependent: :destroy
  has_one :entity_type
end

app/models/coreman/entity_name.rb
class EntityName < ApplicationRecord
  belongs_to :entity
  has_one :entity_name_type
end

app/models/coreman/entity_name_type.rb
class EntityNameType < ApplicationRecord
  has_many :entity_names
  validates :value, uniqueness: true
end

app/models/coreman/entity_type.rb
class EntityType < ApplicationRecord
  has_many :entities

  validates :value, uniqueness: true
end

app/models/exempla/exempla_product.rb
class ExemplaProduct < ApplicationRecord
  has_rich_text :description
  validates :name, presence: true
  has_one_attached :featured_image
end

app/models/exempla/product.rb
class Exempla::Product < ApplicationRecord
  has_rich_text :description
  validates :name, presence: true

  has_one_attached :featured_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authentication/passwords_controller.rb
class Authentication::PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_authentication_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_authentication_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_authentication_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_authentication_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_authentication_session_path
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_authentication_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/coreman/entities_controller.rb
class Coreman::EntitiesController < ApplicationController
  before_action :set_entity, only: %i[ show edit update destroy ]
  before_action :get_entity_types, only: %i[ index edit update show]
  def index
    @entities ||= Entity.where(user_id: Current.user[:id])
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def entity_params
    params.expect(entity: [ :display_name, :description, :user_id, :entity_type_id ])
  end

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def get_entity_types
    @entity_types ||= {}
    EntityType.all.each { |t| @entity_types[t[:id]] = t[:value] } if @entity_types.empty?
  end
end

app/controllers/exempla/products_controller.rb
class Exempla::ProductsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show]
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = ExemplaProduct.all
  end

  def show
  end

  def new
    @product = ExemplaProduct.new
  end

  def create
    @product = ExemplaProduct.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to exempla_products_path
  end

  private

  def product_params
    params.expect(exempla_product: [ :name, :description, :featured_image ])
  end

  def set_product
    @product = ExemplaProduct.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  allow_unauthenticated_access
  def home
  end

  def exempla
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coreman/entities_helper.rb
module Coreman::EntitiesHelper
end

app/helpers/exempla/products_helper.rb
module Exempla::ProductsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/coreman/entities/index.html.erb
<h1> Entities </h1>
<div>
  <% @entities.each do |e| %>
  <div>
    <b> <%= @entity_types[e.entity_type_id] %> </b> | 
      <%= link_to e.display_name, coreman_entity_path(e.id) %> |
    <i> <%= e.description %> </i>
  </div>
  <% end %>
</div>

app/views/coreman/entities/show.html.erb
<%= link_to "Back", coreman_entities_path %>

<h1> <%= @entity.display_name %> </h1>
<div>
  <b> Type: </b> <%= @entity_types[@entity.entity_type_id] %>
</div>
<div>
  <b> Description: </b> <%= @entity.description %>
</div>

app/views/exempla/products/_form.html.erb
<script type="text/javascript">

document.addEventListener("trix-file-accept", (event) => {
  event.preventDefault();
});

</script>

<%= form_with model: exempla_product do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>

    </p>
    <%= f.label :featured_image, style: "display: block" %>
      <% if @product.featured_image.attached? %>
        <%= image_tag @product.featured_image, class: "image-profile-pic" %></br>
      <% end %>
      <%= f.file_field :featured_image, accept: "image/*" %></br>

    </p>
    <div class="product-description">
      <%= f.label "Product Description" %>
      <%= f.rich_text_area :description %>
    </div>
  <div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/exempla/products/edit.html.erb
<h1>Edit product</h1>

<%= render "form", exempla_product: @product %>
<%= link_to "Cancel", @product %>

app/views/exempla/products/index.html.erb
<h1>Products#index</h1>
<div id="products">
  <% @products.each do |p| %>
    <div>
      <%= link_to p.name, p %>
    </div>
  <% end %>
</div>

</p><%= link_to "Add Product", new_exempla_product_path if authenticated? %>

app/views/exempla/products/new.html.erb
<h1>New product</h1>

<%= render "form", exempla_product: @product %>
<%= link_to "Cancel", exempla_products_path %>

app/views/exempla/products/show.html.erb
<% cache @product do %>
  <h1><%= @product.name %></h1>

  <% if @product.featured_image.attached? %>
    <%= image_tag @product.featured_image, class: "image-profile-pic" %>
  <% end %>

  <%= @product.description %>
  
<% end %>

<%= link_to "Back", exempla_products_path %> </br>
<% if authenticated? %>
  <%= link_to "Edit", edit_exempla_product_path(@product) %> </br>
  <%= button_to "Delete", @product, method: :delete, data: { turbo_confirm: "Are you sure?" } %>
<% end %>