config/routes.rb
Rails.application.routes.draw do
  # get "pages/exempla", to: "pages#exempla"
  namespace :pages do
    get "/exempla", to: "exempla" # equivalent to <get "pages/exempla", to: "pages#exempla"> outside of namespace
    get "/index", to: "index"
  end

  namespace :exempla do
    resources :products
  end

  namespace :coreman do
    resources :entities
  end

  namespace :authentication do
    resource :session
    resources :passwords, param: :token
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/authentication/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/authentication/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :email_address, uniqueness: true

  has_many :entities, dependent: :destroy

  def set_defaults
    self.confirmed_email = false
  end
end

app/models/coreman/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :entity_names, dependent: :destroy
  has_one :entity_type
end

app/models/coreman/entity_name.rb
class EntityName < ApplicationRecord
  belongs_to :entity
  has_one :entity_name_type
end

app/models/coreman/entity_name_type.rb
class EntityNameType < ApplicationRecord
  has_many :entity_names
  validates :value, uniqueness: true
end

app/models/coreman/entity_type.rb
class EntityType < ApplicationRecord
  has_many :entities

  validates :value, uniqueness: true
end

app/models/exempla/exempla_product.rb
class ExemplaProduct < ApplicationRecord
  has_rich_text :description
  validates :name, presence: true
  has_one_attached :featured_image
end

app/models/exempla/product.rb
class Exempla::Product < ApplicationRecord
  has_rich_text :description
  validates :name, presence: true

  has_one_attached :featured_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_authentication_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_authentication_session_path
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_authentication_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/coreman/entities_controller.rb
class Coreman::EntitiesController < ApplicationController
  before_action :set_entity, only: %i[ show edit update destroy ]
  before_action :get_entity_types, only: %i[ index edit update show]
  def index
    @entities ||= Entity.where(user_id: Current.user[:id])
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def entity_params
    params.expect(entity: [ :display_name, :description, :user_id, :entity_type_id ])
  end

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def get_entity_types
    @entity_types ||= {}
    EntityType.all.each { |t| @entity_types[t[:id]] = t[:value] } if @entity_types.empty?
  end
end

app/controllers/exempla/products_controller.rb
class Exempla::ProductsController < ApplicationController
  allow_unauthenticated_access only: %i[ index show]
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = ExemplaProduct.all
  end

  def show
  end

  def new
    @product = ExemplaProduct.new
  end

  def create
    @product = ExemplaProduct.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to exempla_products_path
  end

  private

  def product_params
    params.expect(exempla_product: [ :name, :description, :featured_image ])
  end

  def set_product
    @product = ExemplaProduct.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  allow_unauthenticated_access
  def home
  end

  def exempla
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coreman/entities_helper.rb
module Coreman::EntitiesHelper
end

app/helpers/exempla/products_helper.rb
module Exempla::ProductsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Co Re Man" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class = "navigation_menu">
      
      <%= link_to "Home", root_path, :class => "nav_button" %>

      <% if not authenticated? %>
        <%= link_to "Login", new_authentication_session_path unless authenticated? %>
      <% else %>
        <%=  button_to "Log out", authentication_session_path, class: "nav_button", method: :delete %>
      <% end %>
      
    </nav>
    <div></div class = "border">
  

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/scrap.html.erb
      <%= link_to "Home", root_path, :class => "standard_navigation" %>

app/views/pages/exempla.html.erb
<h1> Exempla </h1>

<%= link_to "Products", exempla_products_path %>

app/views/pages/home.html.erb
<h1>Welcome Home</h1>

<%= link_to "Exempla", "/pages/exempla" %><br>
<%= link_to "Coreman:Entities", coreman_entities_path %><br>
<%= link_to "Index", "/pages/index" %>